// <auto-generated />
using System;
using GraphQLAdvanced.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GraphQLAdvanced.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210919131916_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("GraphQLAdvanced.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ownerId");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f176a63-bc68-496c-b3a9-bde32939ea9c"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("1a5af26f-6ba0-4706-b8fc-402ccdb71fa6"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("1ece43db-bcce-4b1a-bd1a-1387938caaa6"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("8e1caea5-569d-4dff-b41d-4b69cfdca5fe"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("f6beea8c-11ef-43f4-9474-40fde8b855c3"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("8e1caea5-569d-4dff-b41d-4b69cfdca5fe"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("GraphQLAdvanced.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a5af26f-6ba0-4706-b8fc-402ccdb71fa6"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("8e1caea5-569d-4dff-b41d-4b69cfdca5fe"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("GraphQLAdvanced.Entities.Account", b =>
                {
                    b.HasOne("GraphQLAdvanced.Entities.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GraphQLAdvanced.Entities.Owner", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
